package: health
output: internal/handlers/health/gen.go
generate:
  strict-server: true
  models: true
import-mapping:
  './components.yaml': github.com/fido-device-onboard/go-fdo-server/internal/handlers/components
output-options:
  skip-prune: true