on:
  push:
    branches:
    - main
  pull_request:

name: Container Tests

jobs:
  test-container-onboarding:
    name: Test FIDO device onboarding
    runs-on: ubuntu-latest
    steps:

      - name: Install golang
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Test FIDO device onboarding
        id: onboarding
        run: |
          source test/container/test-onboarding.sh
          run_test

      - name: Get manufacturer, rendezvous and owner server logs
        if: always()
        run: |
          source test/container/test-onboarding.sh
          get_logs

      - name: Cleanup the environment
        if: always()
        run: |
          source test/container/test-onboarding.sh
          cleanup

  test-container-onboarding-postgres:
    name: Test FIDO device onboarding (PostgreSQL)
    runs-on: ubuntu-latest
    steps:

      - name: Install golang
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Test FIDO device onboarding
        id: onboarding
        run: |
          source test/container/test-onboarding-postgres.sh
          run_test

      - name: Get manufacturer, rendezvous and owner server logs
        if: always()
        run: |
          source test/container/test-onboarding-postgres.sh
          get_logs

      - name: Cleanup the environment
        if: always()
        run: |
          source test/container/test-onboarding-postgres.sh
          cleanup


  test-container-ov-verification:
    name: Test Ownership Voucher verification
    runs-on: ubuntu-latest
    steps:

      - name: Install golang
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Test Ownership Voucher verification
        run: |
          source test/container/test-ov-verification.sh
          run_test

      - name: Get manufacturer, rendezvous and owner server logs
        if: always()
        run: |
          source test/container/test-ov-verification.sh
          get_logs

      - name: Cleanup the environment
        if: always()
        run: |
          source test/container/test-ov-verification.sh
          cleanup

  test-container-resale:
    name: Test FIDO resale protocol
    runs-on: ubuntu-latest
    steps:

      - name: Install golang
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Test FIDO resale protocol
        run: |
          source test/container/test-resale.sh
          run_test

      - name: Get manufacturer, rendezvous and owner server logs
        if: always()
        run: |
          source test/container/test-resale.sh
          get_logs

      - name: Cleanup the environment
        if: always()
        run: |
          source test/container/test-resale.sh
          cleanup

  test-container-fsim-fdo-upload:
    name: Test FSIM fdo.upload
    runs-on: ubuntu-latest
    steps:

      - name: Install golang
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Test FSIM fdo.upload
        run: |
          source test/container/test-fsim-upload.sh
          run_test

      - name: Get manufacturer, rendezvous and owner server logs
        if: always()
        run: |
          source test/container/test-fsim-upload.sh
          get_logs

      - name: Cleanup the environment
        if: always()
        run: |
          source test/container/test-fsim-upload.sh
          cleanup

  test-container-fsim-fdo-download:
    name: Test FSIM fdo.download
    runs-on: ubuntu-latest
    steps:

      - name: Install golang
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Test FSIM fdo.download
        run: |
          source test/container/test-fsim-download.sh
          run_test

      - name: Get manufacturer, rendezvous and owner server logs
        if: always()
        run: |
          source test/container/test-fsim-download.sh
          get_logs

      - name: Cleanup the environment
        if: always()
        run: |
          source test/container/test-fsim-download.sh
          cleanup

  test-container-fsim-fdo-wget:
    name: Test FSIM fdo.wget
    runs-on: ubuntu-latest
    steps:

      - name: Install golang
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Test FSIM fdo.wget
        run: |
          source test/container/test-fsim-wget.sh
          run_test

      - name: Get manufacturer, rendezvous and owner server logs
        if: always()
        run: |
          source test/container/test-fsim-wget.sh
          get_logs

      - name: Cleanup the environment
        if: always()
        run: |
          source test/container/test-fsim-wget.sh
          cleanup

  test-container-onboarding-config:
    name: Test FIDO device onboarding using a configuration file
    runs-on: ubuntu-latest
    steps:

      - name: Install golang
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Test FIDO device onboarding
        id: onboarding
        run: |
          source test/container/test-onboarding-config.sh
          run_test

      - name: Get manufacturer, rendezvous and owner server logs
        if: always()
        run: |
          source test/container/test-onboarding-config.sh
          get_logs

      - name: Cleanup the environment
        if: always()
        run: |
          source test/container/test-onboarding-config.sh
          cleanup

  test-container-device-ca-api:
    name: Test Device CA API
    runs-on: ubuntu-latest
    steps:

      - name: Install golang
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Test Device CA API
        run: |
          source test/container/test-device-ca-api.sh
          run_test

      - name: Get manufacturer, rendezvous and owner server logs
        if: always()
        run: |
          source test/container/test-device-ca-api.sh
          get_logs

      - name: Cleanup the environment
        if: always()
        run: |
          source test/container/test-device-ca-api.sh
          cleanup

  test-container-device-ca-owner-trust:
    name: Test Device CA owner trust verification
    runs-on: ubuntu-latest
    steps:

      - name: Install golang
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Test Device CA owner trust verification
        run: |
          source test/container/test-device-ca-owner-trust.sh
          run_test

      - name: Get manufacturer, rendezvous and owner server logs
        if: always()
        run: |
          source test/container/test-device-ca-owner-trust.sh
          get_logs

      - name: Cleanup the environment
        if: always()
        run: |
          source test/container/test-device-ca-owner-trust.sh
          cleanup

  test-container-device-ca-rendezvous-trust:
    name: Test Device CA rendezvous trust verification
    runs-on: ubuntu-latest
    steps:

      - name: Install golang
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Test Device CA rendezvous trust verification
        run: |
          source test/container/test-device-ca-rendezvous-trust.sh
          run_test

      - name: Get manufacturer, rendezvous and owner server logs
        if: always()
        run: |
          source test/container/test-device-ca-rendezvous-trust.sh
          get_logs

      - name: Cleanup the environment
        if: always()
        run: |
          source test/container/test-device-ca-rendezvous-trust.sh
          cleanup
