on:
  push:
    branches:
    - main
  pull_request:

name: Go test coverage

jobs:
  coverage:
    name: Measure test coverage (unit + integration tests)
    runs-on: ubuntu-latest
    steps:
      - name: Install golang
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Run tests with coverage
        run: make test-coverage

      - name: Download base coverage breakdown
        id: download-main-breakdown
        uses: dawidd6/action-download-artifact@v6
        with:
          branch: main
          workflow_conclusion: success
          name: main.breakdown
          if_no_artifact_found: warn

      # continue-on-error: allow workflow to proceed to post PR comment and upload artifacts
      - name: Check coverage thresholds
        id: coverage
        uses: vladopajic/go-test-coverage@v2
        continue-on-error: true
        with:
          config: .testcoverage.yml
          breakdown-file-name: ${{ github.ref_name == 'main' && 'main.breakdown' || '' }}
          diff-base-breakdown-file-name: ${{ steps.download-main-breakdown.outputs.found_artifact == 'true' && 'main.breakdown' || '' }}

      - name: Find pull request ID
        run: |
          PR_DATA=$(curl -s -H "Authorization: token ${{ github.token }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?head=${{ github.repository_owner }}:${{ github.head_ref || github.ref_name }}&state=open")
          PR_ID=$(echo "$PR_DATA" | jq -r '.[0].number')
          if [ "$PR_ID" != "null" ]; then
            echo "pull_request_id=$PR_ID" >> "$GITHUB_ENV"
          else
            echo "No open pull request found for branch ${{ github.head_ref || github.ref_name }}."
          fi

      - name: Post coverage report to PR
        if: env.pull_request_id
        uses: thollander/actions-comment-pull-request@v3
        with:
          github-token: ${{ github.token }}
          comment-tag: coverage-report
          pr-number: ${{ env.pull_request_id }}
          message: |
            `go-test-coverage` report
            ```
            ${{ fromJSON(steps.coverage.outputs.report) }}```

      - name: Upload coverage breakdown
        uses: actions/upload-artifact@v4
        if: github.ref_name == 'main'
        with:
          name: main.breakdown
          path: main.breakdown
          if-no-files-found: error

      - name: Generate HTML report
        if: always()
        run: go tool cover -html=coverage.out -o coverage.html

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.html

      # fail the workflow if coverage thresholds are not met, after PR comment and artifacts are posted
      - name: Fail if coverage thresholds not met
        if: steps.coverage.outcome == 'failure'
        shell: bash
        run: echo "Coverage thresholds are not met." && exit 1
